In [ ]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = {
    'Passenger_ID': ['ABVWIg', 'jkXXAX', 'CdUz2g', 'BRS38V', '9kvTLo'],
    'First_Name': ['Edithe', 'Elwood', 'Darby', 'Dominica', 'Bay'],
    'Last_Name': ['Leggis', 'Catt', 'Felgate', 'Pyle', 'Pencost'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Age': [62, 62, 67, 71, 21],
    'Nationality': ['Japan', 'Nicaragua', 'Russia', 'China', 'China'],
    'Airport_Name': [
        'Coldfoot Airport',
        'Kugluktuk Airport',
        'Grenoble-Isère Airport',
        'Ottawa / Gatineau Airport',
        'Gillespie Field'
    ],
    'Airport_Country_Code': ['US', 'CA', 'FR', 'CA', 'US'],
    'Country_Name': [
        'United States',
        'Canada',
        'France',
        'Canada',
        'United States'
    ],
    'Airport_Continent': ['NAM', 'NAM', 'EU', 'NAM', 'NAM'],
    'Continents': [
        'North America',
        'North America',
        'Europe',
        'North America',
        'North America'
    ],
    'Departure_Date': [
        '6/28/2022',
        '12/26/2022',
        '1/18/2022',
        '9/16/2022',
        '2/25/2022'
    ],
    'Arrival_Airport': ['CXF', 'YCO', 'GNB', 'YND', 'SEE'],
    'Pilot_Name': [
        'Fransisco Hazeldine',
        'Marla Parsonage',
        'Rhonda Amber',
        'Kacie Commucci',
        'Ebonee Tree'
    ],
    'Flight_Status': [
        'On Time',
        'On Time',
        'On Time',
        'Delayed',
        'On Time'
    ]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

,Passenger_ID,First_Name,Last_Name,Gender,Age,Nationality,Airport_Name,Airport_Country_Code,Country_Name,Airport_Continent,Continents,Departure_Date,Arrival_Airport,Pilot_Name,Flight_Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time

In [ ]:
#encode categorical -> Numeric
le = {}  # create empty dictionary
df_enc = df.copy()  # here we just cop our original data
for col in df.columns:  # it convert into the text using loop through of the c
    le[col] = LabelEncoder()  # now create new label for current data
    df_enc[col] = le[col].fit_transform(df[col])

In [ ]:
df_enc

,Passenger_ID,First_Name,Last_Name,Gender,Age,Nationality,Airport_Name,Airport_Country_Code,Country_Name,Airport_Continent,Continents,Departure_Date,Arrival_Airport,Pilot_Name,Flight_Status
0,1,3,2,0,1,1,0,2,2,1,1,3,0,1,1
1,4,4,0,1,1,2,3,0,0,1,1,1,3,3,1
2,3,1,1,1,2,3,2,1,1,0,0,0,1,4,1
3,2,2,4,0,3,0,4,0,0,1,1,4,4,2,0
4,0,0,3,1,0,0,1,2,2,1,1,2,2,0,1

In [ ]:
x = df_enc[['Gender', 'Age', 'Nationality',
            'Airport_Name', 'Airport_Country_Code',
            'Country_Name', 'Airport_Continent',
            'Continents', 'Arrival_Airport',
            'Pilot_Name']]

y = df_enc['Flight_Status']

In [ ]:
x

,Gender,Age,Nationality,Airport_Name,Airport_Country_Code,Country_Name,Airport_Continent,Continents,Arrival_Airport,Pilot_Name
0,0,1,1,0,2,2,1,1,0,1
1,1,1,2,3,0,0,1,1,3,3
2,1,2,3,2,1,1,0,0,1,4
3,0,3,0,4,0,0,1,1,4,2
4,1,0,0,1,2,2,1,1,2,0

In [ ]:
y

0    1
1    1
2    1
3    0
4    1
Name: Flight_Status, dtype: int64

In [ ]:
model = CategoricalNB() #apply model
model.fit(x,y) #here fit your values

CategoricalNB()

In [ ]:
test = [['Female',
         21,
         'Japan',
         'Coldfoot Airport',
         'US',
         'United States',
         'NAM',
         'North America',
         'CXF',
         'Fransisco Hazeldine']] #testing data

In [ ]:
test

[['Female',
  21,
  'Japan',
  'Coldfoot Airport',
  'US',
  'United States',
  'NAM',
  'North America',
  'CXF',
  'Fransisco Hazeldine']]

In [ ]:
print("\n--------Prediction---------------------------")

for t in test:
    row = [[
        le['Gender'].transform([t[0]])[0],
        le['Age'].transform([t[1]])[0],  # Transform Age using its LabelEncoder
        le['Nationality'].transform([t[2]])[0],
        le['Airport_Name'].transform([t[3]])[0],
        le['Airport_Country_Code'].transform([t[4]])[0],
        le['Country_Name'].transform([t[5]])[0],
        le['Airport_Continent'].transform([t[6]])[0],
        le['Continents'].transform([t[7]])[0],
        le['Arrival_Airport'].transform([t[8]])[0],
        le['Pilot_Name'].transform([t[9]])[0]
    ]]

    pred = le['Flight_Status'].inverse_transform(model.predict(row))[0]
    prob = model.predict_proba(row)[0]

    print(f"Input: Gender={t[0]}, Age={t[1]}, Nationality={t[2]}")
    print(f"Predicted Flight Status = {pred}")

    for i, status in enumerate(le['Flight_Status'].classes_):
        print(f"P({status}) = {prob[i]:.4f}")

    print("-" * 50)

--------Prediction---------------------------
Input: Gender=Female, Age=21, Nationality=Japan
Predicted Flight Status = On Time
P(Delayed) = 0.0439
P(On Time) = 0.9561
--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x)
print(f"\nTraining Accuracy: {accuracy_score(y,y_pred)*100:.2f}%")

Training Accuracy: 100.00%